name: 01 Basic Docker Build Vote
# simplest workflow possible

on:
  push:
    branches:
      - main
    paths:
      - vote/**
      - .github/workflows/call-docker-build-vote.yaml
  pull_request:
    branches:
      - main
    paths:
      - vote/**
      - .github/workflows/call-docker-build-vote.yaml

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: dockerspange/docker-ci-automation:latest,dockerspange/docker-ci-automation:01
