---
name: 03 Build with Multi-Platform

on:
  push:
    branches:
      - main
    paths:
      - result/**
      - .github/workflows/call-docker-build-result.yaml
  pull_request:
    branches:
      - main
    paths:
      - result/**
      - .github/workflows/call-docker-build-result.yaml

jobs:
  call-docker-build:
    name: Call Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: dockerspange/docker-ci-automation:03
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: "{{defaultContext}}:result"